### ISSUE TITLE
[OE] Rasising 100% Test Coverage Existing Primitives

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#1]
# Context

Studio, editor and primitives live in the same repository. We need to decouple primitives to their own repos and increase coverage to 100% in unit tests.

# Tasks
- [x] Coverage Wallet Connect
- [x] Coverage Web3 Forms
- [x] Coverage Toast

# Acceptance Criteria
- [x] As Webstudio developer, I can work on modular repositories with 100% coverage enforced on pre-commit hook
