### ISSUE TITLE
[FEATURE] Basic Blocks

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#10]
# Context

When building apps we don't have basic components such as iFrame, image, svg.

# Tasks
- [ ] Create a section for basic HTML components and a way to configure them
- [ ] Create a new repository with these basic modules
- [ ] New style for all blocks

# Acceptance Criteria
- [ ] As a builder I can drag and drop and configure basic html modules
