### ISSUE TITLE
[Plugin Marketplace] Blocks API

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#100]
# Context

Today, all blocks are embedded in the studio repository. To scale and allow people to build their own blocks we need to move to configurable blocks via API.

The idea is to have blocks be repositories in Github and have an indexer API endpoint

# Tasks
* [ ] API endpoint GET  /blocks all blocks (queryparam filter by category) retrieves id, name, svg image, category, author (0x, email, name) github repo url
* [ ] API endpoint POST /blocks all blocks (queryparam filter by category) retrieves id, name, svg image, category, author (0x, email, name) github repo url
* [ ] Lambda
* [ ] DDB Table
* [ ] Studio UI to retrieve blocks from endpoint
* [ ] Migrate all blocks to endpoint and remove from codebase
* [ ] Sample repo (boilerplate)

# Acceptance Criteria
* [ ] As an admin I can create blocks without having to deploy new versions of the studio so that I can focus on content and extend for other builders to create components in the future.
