### ISSUE TITLE
[Plugin Marketplace] Templates API

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#101]
# Context

Today, all templates are embedded in the studio repository. To scale and allow people to build their own templates we need to move to configurable templates via API.

The idea is to have templates be repositories in Github and have an indexer API endpoint

# Tasks
* [x] API endpoint GET  /templates all templates (queryparam filter by category) retrieves id, name, svg image, category, description, tags, author (0x, email, name) github repo url for source
* [x] Lambda
* [x] DDB Table
* [x] Studio UI to retrieve templates from endpoint
* [x] Migrate all templates to endpoint and remove from codebase

# Acceptance Criteria
* [x] As an admin I can create templates without having to deploy new versions of the studio so that I can focus on content and extend for other builders to create templates in the future.
