### ISSUE TITLE
[Feature] Analytics

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#102]
# Context

As of today, Webstudio projects have no way of analyzing or tracking metrics. This feature will enable a new dashboard from Google Analytics and to track events. We will be using the embed API https://developers.google.com/analytics/devguides/reporting/embed/v1/getting-started

Analytics to track:
- Users, new users, conversions and event count
- Total revenue
- Users by country
- User activity by cohort

# Tasks
* [ ] Create new menu item in Studio UI for analytics
* [ ] Default analytics dashboard requires sending GA ID and tracking
* [ ] API enable to store and retrieve GA fields from project DDB
* [ ] Dashboard pulls analytics embed from GA
* [ ] Link to full GA

# Acceptance Criteria
* [ ] As a builder I can confgure my analytics dashboard with GA and view the most important metrics so that I can know the state of my projects and my users
