### ISSUE TITLE
[FEATURE] Animations and Custom JS Behavior

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#11]
# Context

Improve current animation functionality and add the ability to add custom code to enhance the experience

# Tasks
- [x] Add more animations from animate.css
- [x] Add custom JS for components

# Acceptance Criteria
- [x] As a builder I can choose for a larger range of animations and add custom code in javascript
