### ISSUE TITLE
[Operational Excellence] Migrate From Moralis To Filebase For IPFS

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#110]
# Context

Moralis IPFS management has been subpar with regards to communicating brekaing changes and tied to several high impact issues such as the [downtime in June 2023](https://mirror.xyz/gianksp.eth/qGkk38cfScZrgCWDAAsBG4jVzWr774aeg_RsXVEfYy0). We have recently joined Filebase startup program and obtained credits for using it.

The objective is to migrate to Filebase all IPFS related operations.

# Tasks
* [ ] Setup Filebase and create a gateway for Webstudio
* [ ] Refactor media upload logic to use Filebase
* [ ] Refactor app publishing logic to use Filebase
* [ ] Refactor Lambda subdomain handler function to use Filebase

# Acceptance Criteria
* [ ] As a builder when I publish my app and visit my link, it immediately shows my updated version without having to refresh several times
* [ ] As an admin I see lower incidence of 502 gateway error because access to CID is immediate from gateway
