### ISSUE TITLE
[SERVICE] Decentralized Open Source Blog Service

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#13]
# Context

Ghost is a platform that allows to create blogs, this is an [example](https://medium.com/pinata/how-to-build-an-nft-token-gated-blog-72589be36030) on how to use IPFS to launch blogs. Create the infra to launch blogs without code

# Tasks
- [ ] PoC Ghost [integration with AWS lightsail ](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-quick-start-guide-ghost)
- [ ] Certificate generation and subdomain generation
- [ ] Launcher from Webstudio or standalone for HackFS
- [ ] Only for Premium plans

# Acceptance Criteria
- [ ] A builder can launch infrastructure in lightsail
