### ISSUE TITLE
[OE] Decoupling Primitives

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#2]
# Context

Studio, editor and primitives live in the same repository. We need to decouple primitives to their own repos.

# Tasks
- [x] New repos for all primitives within studio
- [x] Remove primitives from studio folder and import as dependency instead
- [x] Migrate Wallet Connect
- [x] Migrate Web3 Forms

# Acceptance Criteria
- [x] As Webstudio developer, I can work on modular repositories
