### ISSUE TITLE
[FEATURE] Download source code from application

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#21]
# Context

Include a way to download the source code of the application built in with Webstudio in order to run it locally

# Tasks
- [ ] HTML
- [ ] CSS
- [ ] Javascript
- [ ] Headers and meta
- [ ] Tutorial

# Acceptance Criteria
- [ ] As a user I can download my website source code, uncompress it and run it locally
- [ ] As a user I have a tutorial where I can get guidance on how to do this
