### ISSUE TITLE
[BLOCKS] Token Gated Section

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#50]
# Context

Add to HTML "sections" the capabilities to be NFT token gated, meaning only those who comply with the rules can access the content. Rules will be simple for this version:

- User owns any NFT from collection (721, 1155)
- User owns specific token id (from comma separated list of ids)

# Tasks
- [x] Create new section block for drag and drop
- [x] Wizard: Network, contract address, tokenIds (optional, comma separated if many)

# Acceptance Criteria
- [x] As a builder I can configure a section of the app only visible to those who hold NFTs of my choosing. I can even specify specific IDs from the collection optionally.
