### ISSUE TITLE
[IMPROVEMENT] Copilot Full Template Generation

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#51]
# Context

Copilot needs to be able to generate full templates, including content from prompts. Create a guided experience to build custom templates using prompts like below.

# Tasks
- [ ] Remove copilot as a chat, make it more targeted based on need.
- [ ] On Template Page: add "Create new" button
- [ ] Create a new full-screen wizard with the objective of creating a full template. Similar to the create project experience, we will ask for different parameters that will feed chat gpt ws api and build by blocks on the frontend. 
- [ ] We can reuse this wizard for section generation.

# Acceptance Criteria
- [ ] As a builder I can prompt to generate new templates and preview them. I can also select a template from prompts to replace my current styles.

# Example prompt

```
Create a website home page with extra large padding. There should be a hero section followed by 13 different ‘non-hero-sections’. Each section should be designed differently from the one before it. The hero section should have a full width background image placeholder and a small image placeholder in the top left; also a button in the top right, and a 3-item menu to the left of that button with white text. The H1 in the hero section  should have at least 30px of padding around it. Each ‘non-hero-section’ should contain 2 columns. ALL ‘non-hero-sections’ should have the same VERY light grey background color, and they should ALL utilize the same two fonts. ALL sections should include a medium-sized square placeholder image within one of the columns that doesn’t contain text. Every section should have an button below the text with a gradient fill and a white border with white text saying ‘Schedule a Demo’. The buttons should each have their corners rounded 16 px and a subtle drop shadow.

Break-up the ’marketing script’ (which I’ll provide below) into each of the ‘non-hero-sections’ the text should all be dark grey and have at least 32px of padding all around. Use all of the marketing script. Don’t change it, and don’t exclude any of it! Here’s the ‘marketing script’: 

“Investing can feel confusing, but we make it fun and accessible for freelancers like you! Schedule a Demo today and start your journey to financial independence.

Discover the power of micro-investments – you don't need to be rich to see big returns. No matter your earnings, you deserve access to great investment opportunities. Schedule a Demo and begin investing with as little as $8 a month.
Build confidence, spot trends, and earn passive income with our automated micro-investment platform. Become a strategic investor and enjoy more peace of mind. Schedule a Demo now and set a loss limit or pause anytime!
Don't just take our word for it – hear from happy clients like this one: "I wish I knew about this earlier. I was stressed out by the idea of investing, but setup was easy, and I just let it run. Now I feel like a strategic money-planner." Schedule a Demo and join the growing community of successful investors we've helped.
Waiting to invest means missing out on valuable opportunity. Lazy investors risk losing big, but our platform makes it simple to diversify your investments. Schedule a Demo and learn how we've empowered over 900 people to achieve financial independence and peace of mind.
Our founder, Jeff, spent 8 years managing investment portfolios for wealthy clients. He believes everyone should have access to smart investment strategies. Our financial aids are all certified chartered professional accountants – ready to help you succeed.
Schedule a Demo and receive a free download of 'How Wealthy People Think: 18 frameworks to change the way you think about money.' Don't delay – start your journey to financial success today.”

```
