### ISSUE TITLE
[UX] What's New

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#53]
# Context

Users need to know if something new has launched or fixed. One proposal to align the newsletter, SEO and engagement goals is to create a blog entry for each new release each friday:
- What was released or fixed
- Image to showcase it
- Why it matters
- How to use it description and also  a videeo in youtube

This can be displayed on the landing page

# Tasks
- [x] Content pipeline for this year releases
- [ ] Landing page implementation
- [ ] Add a link to the changelog in the landing page from the editor
- [ ] Display in the editor the latest change as a modal

# Acceptance Criteria
- [ ] As a builder I can see what was the latest launch about and I can track the history of changes as well
