### ISSUE TITLE
[CMS] Dynamic and API Collections (Smart Labels)

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#55]
# Context

Sometimes we need to display content in our site that comes from an API request, for example, the Ethereum user balance or to display an NFT to mint so we manually build the card but we need to map the image, title, description, formatted price in currency etc. 

# Tasks
- [ ] Map an API call to a collection
- [ ] Have pre-defined mappings from Moralis and Alchemy API for NFT and token retrievals
- [ ] Allow custom API mapping to a collection

# Acceptance Criteria
- [ ] As a builder, I can create a collection that feeds from API instead of storing data in the platform
