### ISSUE TITLE
[CMS] Collections

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#57]
# Context

Users can create custom collections of data and maintain them. These data collections are available as "API" under `<project>.webstudio.so/_collection/<id>/<item-id>`

# Tasks
- [ ] New side section in editor to manage collections
- [ ] List existing collections
- [ ] Create new collection expands manager for collection
- [ ] On collection manager we can edit the schema (top) or manage the items (below)
- [ ] Schema allows to have fields as image (upload to ipfs and store url only), text, number, date. No nesting allowed.
- [ ] Collections API similar to projects, search by project subdomain
- [ ] On delete project delete collections associated

# Acceptance Criteria
- [ ] As a user I can create a collection with a custom structure and add items to the collection including images, text, etc and can view them on my project url
