### ISSUE TITLE
[CMS] Dynamic Lists And Elements

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#58]
# Context

Now that we have collections we can map content on our app to that data.

# Tasks
- [ ] Content mapping, where we can map a container to a collection, we can map any children of that collection to any field in the collection model. Each field will render its value/src from the parent container data
- [ ] Web3 Button action mapping fields to collection schema field

[ Container - Collection Mapping]
     [Container - Index/Item ID]
             [Text - Item.description]
             [Image - Item.image]
             [Web3 Button (internal mapping using collection)]
     [Container]
[ Container]

# Acceptance Criteria
- [ ] As a builder, I can create a collection that feeds from API instead of storing data in the platform
