### ISSUE TITLE
[CMS] Dynamic Pages

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#59]
# Context

Now that we have collections we can map pages to specific entries. For example in a _collection/a/1 we can map the whole collection to a page when creating, for example mynewpage -> a where we will be able to view the page under mynewpage/1, etc.

# Tasks
- [ ] On page creation define page property mapping to collectiona and the collection name and store it in API content
- [ ] On the page manager I can see all the different pages for the collection but any change I do to the page will reflect in all pages
- [ ] On dynamic pages I can map Lists and Elements to fields based on the path id for the collection the page is mapped

# Acceptance Criteria
- [ ] As a builder I can create a blog, or an NFT gallery for collections etc so that I can create more dynamic content
