### ISSUE TITLE
[OE] Test Coverage 25%

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#60]
# Context

Increase test coverage threshold to 25% pre-commit

# Tasks
- [ ] Increase threshold validation on package.json
- [ ] Create unit tests needed to reach 25%
- [ ] Github coverage badge

# Acceptance Criteria
- [ ] As a guest I can see test coverage on the studio in github at 25% or above
