### ISSUE TITLE
[EDITOR] HTML Navigation Hierarchy Explorer

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#61]
# Context

When selecting a component display all parents as links similar to the edit bar so people can navigate quickly. It can display the tagName and the ID

# Tasks
- [ ] When selecting a component display all parents
- [ ] When clicking on a parent link select that parent

# Acceptance Criteria
- [ ] Ss a builder I can quickly identify parent and navigate without having to click on the up arrow
