### ISSUE TITLE
[THEME] Styles Wizard

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#63]
# Context

We don't want people manually having to add tailwind classes or modifying the style without tailwind classes directly in the editor. Let's create a wizard, similar to wix, capable of modiftying styles, leveraging tailwind properties

# Tasks
- [ ] API of tailwind properties by categories e.g Borders, backgrounds, etc
- [ ] Display as autocomplete, dropdown selectors
- [ ] Add preview of the properties
- [ ] Support All Components

# Acceptance Criteria
- [ ] As a builder I can edit any block or component in the canvas easility, verifying in preview, from selections or simple sliders so that I don't need to remember classes or technical stuff
