### ISSUE TITLE
[AUTOMATION] Custom Domain Management

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#64]
# Context

Supporting custom domain is manually done at the moment:
1. User sends a request via discord on the domain wanted
2. I reach out to confirm the domain
3. I generate a certificate for the domain, clone a cloudfront distribution
4. I send the 2 CNAME (certificate, cloudfront) for user to configure in their DNS provider
5. I finish mapping the cloudfront distribution after certficiate has been approved
6. I add an entry to ddb on the d field for the custom domain to be displayed
7. I notify user the mapping is successful and they can use the platform with their new domain

# Tasks
- [ ] Automate tasks above
- [ ] Create the documentation for users to self service

# Acceptance Criteria
- [ ] As a builder I can self service my way on linking custom domains to Webstudio without need of additional support so that I can build my own app quickly
