### ISSUE TITLE
[COE-1] Website Banner And Log Tracker for High Severity Issues

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#65]
# Context

From the outage suffered due to Moralis permission rules changes explained in [CoE-1](https://mirror.xyz/gianksp.eth/qGkk38cfScZrgCWDAAsBG4jVzWr774aeg_RsXVEfYy0) we will add a banner to the website whenever we have an issue and when a user clicks on the banner we will redirect them to a log tracker on how the issue is being solved and the latest updates.

# Tasks
- [x] Optional Banner styled, hidden
- [x] Process to updating this added to oncall runbook
- [x] Page for managing outage details

# Acceptance Criteria
- [x] As a webstudio user I can be notified if the platform is experiencing issues and be up to date on the progress and impact it has over my applications so that I can have peace of mind.
