### ISSUE TITLE
[COE] OnCall Runbook

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#66]
# Context

From the outage suffered due to Moralis permission rules changes explained in [CoE-1](https://mirror.xyz/gianksp.eth/qGkk38cfScZrgCWDAAsBG4jVzWr774aeg_RsXVEfYy0) we will create a runbook with the steps to debug third party and internal issues, starting with steps to solve incident in CoE-1

# Tasks
- [ ] Create a notion runbook
- [ ] Add the details to debug issues on third party providers (Moralis)

# Acceptance Criteria
- [ ] As a tech team, when an outage occurs I can revert to the runbook and find the root cause and steps to take for resolution and mitigation.
