### ISSUE TITLE
[COE] Third Party Provider Metrics Dashboard

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#67]
# Context

From the outage suffered due to Moralis permission rules changes explained in [CoE-1](https://mirror.xyz/gianksp.eth/qGkk38cfScZrgCWDAAsBG4jVzWr774aeg_RsXVEfYy0) we will create a metrics dashboard with the health of integrations between providers

# Tasks
- [x] IPFS content health on request custom metric
- [x] IPFS content health on request dashboard
- [x] IPFS content health on request alarm

# Acceptance Criteria
- [x] As webstudio tech I can quickly check  a dashboard and identify if content being served via IPFS is responding outside the 200 status code and get notified

**Comment by gianksp** [comment]
Added canaries metric and alarms
