### ISSUE TITLE
[OE] Canary Alarms

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#69]
# Context

From the outage suffered due to Moralis permission rules changes explained in [CoE-1](https://mirror.xyz/gianksp.eth/qGkk38cfScZrgCWDAAsBG4jVzWr774aeg_RsXVEfYy0) we will create canary alarms that check the health of hosted sites with webstudio

# Tasks
- [x] Canary stack infrastructure
- [x] Execute every 5 min check random project reachability and latency
- [x] Dashboard with invocations, latency and error
- [x] Alarm on error loading, alarm on latency over 1 second

# Acceptance Criteria
- [x] As a developer I can count on canary alarms to check the live status of pages hosted with Webstudio so I don't have to do it manually.
