### ISSUE TITLE
[IMPROVEMENT] Clean Project Cache on Publish

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#7]
# Context

When a project is published to IPFS, we don't have an automated way of refreshing the cache of the default and custom domain cloudfronts.

# Tasks
- [ ] On publish refresh the default cache for the project in question
- [ ] On publish refresh the custom cache (if exists) for the project
- [ ] Notify the user to wait a few seconds until cache is cleaned up in the frontend

# Acceptance Criteria
- [ ] As a manager, when launching a new version of my project I get notified I need to wait for the cache clean to finish and when a visitor checks the original URL after cache cleanup finishes, sees the updated version
