### ISSUE TITLE
[FIX] Thumbnails Loading Slow

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#73]
# Context

Template thumbnails and uploaded image thumbnails and images are taking too long to load.

# Tasks
- [ ] Get a dedicated IPFS low-latency provider
- [ ] Update UI routing and retrieval of images
- [ ] Upgrade the IPFS upload mechanism

# Acceptance Criteria
- [ ] As a builder I don't need to wait for images to load while searching templates or uploading images to use on my app
