### ISSUE TITLE
[IMPROVEMENT] Learning Resources Section

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#9]
# Context

When entering the studio is difficult to navigate and know what to do, this task aims to develop a learning repository in Notion.

# Tasks
- [ ] Create a notion-based entry point for resources
- [ ] Tutorials
- [ ] Videos
- [ ] Events and Workshops
- [ ] FAQ

# Acceptance Criteria
- [ ] As a user I can follow a link to learn about how to use the platform
