### ISSUE TITLE
[Automation] Custom Domain: Resource Creation

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#98]
# Context

Managing custom domains involves the following cycle:
1. User requests custom domain from Editor sidemenu (settings). Only available for unlimited
2. A discord notification is received by admin
3. Admin goes into AWS dashboard and clones a cloudfront distribution
4. Admin creates a certificate using AWS certificate manager for the domain, in exchange receives items to add to DNS for the certificate validation
6. Admin goes into AWS dashboard and clones a cloudfront distribution and obtains the url to be added to DNS
7. User receives from admin both CNAME and cert DNS records and configures his cloudflare
8. Admin configures cloudfront distribution (certificate must be valid by this time
9. Admin invalidates cache

This process is manual and even though is fast, a customer leaving requires dissasembling of all these items

# Tasks
* [ ] Capture the email address of each user in the projects they own so they can receive notifications of events. This can be done when creating a project
* [ ] In the UI Submit email address from principal as part of the create project call
* [ ] In the API create a new field to store the email address of the owner
* [ ] Create an SQS for initiating the creation of resources
* [ ] Create a new API endpoint for requesting custom domains
* [ ] Create a Lambda that that generates a certificate for a given custom domain and generates a cloned cloudfront distribution..
* [ ] Once created the distribution and cert add them to the project record in DDB (cert and cname from CF)
* [ ] Allow the retrieval of this information as well on the GET project endpoint and lambda
* [ ] Modify the UI so that users can see the configuration for their domain on settings page
* [ ] Enable SES to send an email with a template notifying the user on the records they must add if email is set
* [ ] Create CW Dashboard for API and lambda for latency, errors, total requests

# Acceptance Criteria
* [ ] As an Unlimited user I can request a custom domain for my project and view in my dashboard the status of the request and which step is pending.
* [ ] As an Unlimited user I receive an email notification when the records are created and the nexts steps I need to take to configure on my DNS.
* [ ] As an Unlimited user I can see the records I need to add to my DNS on my own project editor
* [ ] As a user I can check the operational dashboard and see analytics on the API endpoint and lambda
