### ISSUE TITLE
[Automation] Custom Domain: Resource Configuration

### ISSUE THREAD

**Issue by gianksp** [webstudioso/studio#99]
# Context

Managing custom domains involves the following cycle:
1. User requests custom domain from Editor sidemenu (settings). Only available for unlimited
2. A discord notification is received by admin
3. Admin goes into AWS dashboard and clones a cloudfront distribution
4. Admin creates a certificate using AWS certificate manager for the domain, in exchange receives items to add to DNS for the certificate validation
6. Admin goes into AWS dashboard and clones a cloudfront distribution and obtains the url to be added to DNS
7. User receives from admin both CNAME and cert DNS records and configures his cloudflare
8. Admin configures cloudfront distribution (certificate must be valid by this time
9. Admin invalidates cache

This process is manual and even though is fast, a customer leaving requires dissasembling of all these items

# Tasks
* [ ] Create SQS
* [ ] Create DLQ for requests that fail 72 times
* [ ] When custom domain lambda request creates resources add them to SQS. In the message it adds the project data.
* [ ] Create a lambda that processes those requests every hour
* [ ] The lambda logic checks the status of the certificate, if valid continues with CF config, else errors and tries again.
* [ ] The lambda configures all attributes of CF entry and invalidates cache
* [ ] On success send an email to the project owner saying is ready
* [ ] Create a dashboard for SQS (total requests, time in queue), Lambda (requests, error) and DLQ (total requests, time in queue)

# Acceptance Criteria
* [ ] As an Unlimited user I receive a notification email when my resources are ready and my domain is ready for use
* [ ] As a user I can check a metrics dashboard to see the requests and errors of the lambda and the messages and time in queue on SQS as well as number of messages in DLQ.
